name: Cypress E2E Tests - Firefox

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Cypress Docker image from https://hub.docker.com/r/cypress
    # with browsers pre-installed
    container:
      image: cypress/browsers:latest
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress Run - Firefox
        uses: cypress-io/github-action@v5
        with:
          #build: npm run build
          #start: npm start
          browser: firefox
          record: true
          parallel: true
          # Cancel the run after 2 failed tests
          #auto-cancel-after-failures: 2
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Artifacts Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
      - name: Test Artifacts Videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: ./cypress/videos
